<div class="container-fluid">

      <!-- Side menu --><!-- /Side menu -->

      <!-- Main window --><!-- /row-fluid -->

        <div class="main_container" id="users_page">
          <div class="row-fluid">
            <div class="widget widget-padding span12">
            <div class="widget-header">
              <i class="icon-file-alt"></i>
              <h5>今日任务</h5>
              <div class="widget-buttons">
                  <a href="#" data-title="Add Employee" data-toggle="modal" data-target="#example_modal"><i class="icon-plus"></i></a>
                  <a href="#" data-title="Collapse" data-collapsed="false" class="collapse"><i class="icon-chevron-up"></i></a>
              </div>
            </div>  
            <div class="widget-body" >
              <table class="table">
                <thead>
                  <tr>
                    <th>任务名</th>
                    <th>时间</th>
                    <th>任务状态</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>消除系统bug</td>
                    <td>测试部门</td>
                    <td><span class="label label-success">进行中</span></td>
                    <td>
                      <div class="btn-group">
                        <a class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#">
                        操作
                          <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu pull-right">
                          <li><a href="#"><i class="icon-envelope"></i> 发邮件</a></li>
                          <li><a href="#"><i class="icon-edit"></i> 编辑</a></li>
                          <li><a href="#"><i class="icon-trash"></i> 删除</a></li>
                        </ul>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td>消除系统bug</td>
                    <td>测试部门</td>
                    <td><span class="label">已完成</span></td>
                    <td>
                      <div class="btn-group">
                        <a class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#">
                        操作
                          <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu pull-right">
                          <li><a href="#"><i class="icon-envelope"></i> 发邮件</a></li>
                          <li><a href="#"><i class="icon-edit"></i> 编辑</a></li>
                          <li><a href="#"><i class="icon-trash"></i> 删除</a></li>
                        </ul>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td>消除系统bug</td>
                    <td>测试部门</td>
                    <td><span class="label label-success">进行中</span></td>
                    <td>
                      <div class="btn-group">
                        <a class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#">
                          操作
                          <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu pull-right">
                          <li><a href="#"><i class="icon-envelope"></i> 发邮件</a></li>
                          <li><a href="#"><i class="icon-edit"></i> 编辑</a></li>
                          <li><a href="#"><i class="icon-trash"></i> 删除</a></li>
                        </ul>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td>消除系统bug</td>
                    <td>测试部门</td>
                    <td><span class="label">已完成</span></td>
                    <td>
                      <div class="btn-group">
                        <a class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#">
                          操作
                          <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu pull-right">
                          <li><a href="#"><i class="icon-envelope"></i> 发邮件</a></li>
                          <li><a href="#"><i class="icon-edit"></i> 编辑</a></li>
                          <li><a href="#"><i class="icon-trash"></i> 删除</a></li>
                        </ul>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td>消除系统bug</td>
                    <td>测试部门</td>
                    <td><span class="label label-warning">待完成</span></td>
                    <td>
                      <div class="btn-group">
                        <a class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#">
                          操作
                          <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu pull-right">
                          <li><a href="#"><i class="icon-envelope"></i> 发邮件</a></li>
                          <li><a href="#"><i class="icon-edit"></i> 编辑</a></li>
                          <li><a href="#"><i class="icon-trash"></i> 删除</a></li>
                        </ul>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td>消除系统bug</td>
                    <td>测试部门</td>
                    <td><span class="label">已完成</span></td>
                    <td>
                      <div class="btn-group">
                        <a class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#">
                          操作
                          <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu pull-right">
                          <li><a href="#"><i class="icon-envelope"></i> 发邮件</a></li>
                          <li><a href="#"><i class="icon-edit"></i> 编辑</a></li>
                          <li><a href="#"><i class="icon-trash"></i> 删除</a></li>
                        </ul>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
              <div class="text-center mypages" style="text-align: center;">
                <a href="#">1</a>
                <a href="#">2</a>
                <a href="#">3</a>
                <a href="#">4</a>
              </div>
            </div> <!-- /widget-body -->
          </div> <!-- /widget -->
        </div> <!-- /row-fluid -->


    </div>
      <!-- /Main window -->

    </div><!--/.fluid-container-->
