<div class="container-fluid">

      <!-- Side menu --><!-- /Side menu -->

      <!-- Main window --><!-- /row-fluid -->

        <div class="main_container" id="users_page">
          <div class="row-fluid">
            <div class="widget widget-padding span12">
            <div class="widget-header">
              <i class="icon-file-alt"></i>
              <h5>以后任务</h5>
              <div class="widget-buttons">
                  <a href="/add"><i class="icon-plus"></i></a>
                  <a href="#" data-title="Collapse" data-collapsed="false" class="collapse"><i class="icon-chevron-up"></i></a>
              </div>
            </div>  
            <div class="widget-body" >
              <table class="table">
                <thead>
                  <tr>
                    <th>任务名</th>
                    <th>时间</th>
                    <th>任务状态</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                    {% for item in todos.futrueTodos %}
                        <tr>
                        {% include "../common/_todo-item.phtml" %}
        	           </tr>
                    {% endfor %}  
                </tbody>
              </table>
            </div> <!-- /widget-body -->
          </div> <!-- /widget -->
        </div> <!-- /row-fluid -->


    </div>
      <!-- /Main window -->

    </div><!--/.fluid-container-->
