<div class="container-fluid">

      <!-- Side menu --><!-- /Side menu -->


      <!-- Main window -->
      <div class="main_container" id="dashboard_page">
        <br><!-- /row-fluid -->


        <div class="row-fluid">
          <div class="widget span12">
            <div class="widget-header">
              <i class="icon-envelope-alt"></i>
              <h5>增加</h5>
              <div class="widget-buttons">
                  <a href="javascript:void(0)" class="collapse" data-collapsed="false"><i data-title="Collapse" class="icon-chevron-up"></i></a>
              </div>
            </div>
            <form class="form-horizontal" id="addTodo" method="POST">
            <div class="widget-body" >
              <div class="widget-forms clearfix">
                <br>
                  <div class="control-group">
                    <label class="control-label">主题</label>
                    <div class="controls">
                      <input id="title" name="title" value="{{form.title}}" class="span7" type="text" placeholder="输入主题">
                      <span>{{error.title}}</span>
                    </div>
                  </div>
                <div class="control-group">
                  <label class="control-label">完成时间</label>
                  <div class="controls">
                  <input type="date" id="totoTime" name="todoTime" class="span7" placeholder="格式为：2017-08-01 23:00:00，可以为空">
                    <span>{{error.todoTime}}</span>
                  </div>
                </div>


                  <div class="control-group">
                    <label class="control-label">主要内容</label>
                    <div class="controls">
                      <textarea id="content" name="content" class="span7" rows="5" style="height:100px;" placeholder="输入内容">{{error.content}}</textarea>
                    </div>
                  </div>

                

              </div>

            </div><!--/widget-body-->
            <div class="widget-footer" style="text-align: center;">
              <button class="btn btn-primary" type="submit">确定</button>
              <button class="btn" type="button">取消</button>
              <span>{{error.addError}}</span>
            </div>
            </form>
          </div> <!-- /widget span5 -->


        </div> <!-- /row-fluid -->




      </div>
      <!-- /Main window -->
      
    </div><!--/.fluid-container-->