<div class="footer hidden-elements">
<div class="container">
<!--<div class="hyperlink">
<a href="#">金宝保首页</a>
<span>|</span>
<a href="#">什么是分期</a>
<span>|</span>
<a href="#">配送方式</a>
<span>|</span>
<a href="#">售后服务</a>
</div>-->
<div class="copyright">
<p>版权所有@重庆金宝保信息技术服务有限公司 备案号：渝ICP备<i>14003649</i>号 联系电话：400-863-2766</p>
<p>办公地址：重庆市渝北区金开大道56号两江天地1栋3-4层</p>
</div>
<!-- <div class="safelink"> -->
<!-- <a href="#" target="_blank" class="sSafe"></a> -->
<!-- <a href="https://search.szfw.org/cert/l/CX20140813008676008771" id="___szfw_logo___" target="_blank" class="sincerity"></a> -->
<!-- <a tabindex="-1" class="v_seal" target="_blank" href="https://sealinfo.verisign.com/splash?form_file=fdf/splash.fdf&amp;dn=www.5djbb.com&amp;lang=zh_cn"></a> -->
<!-- <a href="http://beian.cqnet110.gov.cn/open/showRecord?id=50011202000293" target="_blank" class="wangBei"></a> -->
<!-- <a href="http://www.cqgseb.cn" target="_blank" class="wangJian"></a> -->
<!-- <a href="http://cqnet110.gov.cn/" target="_blank" class="sentrybox"></a> -->
<!-- </div> -->
</div>
</div>
