<div class="navMenu threeItems {%if hiddenMenu %} hidden-elements {%endif%}">
  <div class="container">
    <a href="/" {{"/"|navactive}} ><i class="visible-elements webicon icon-home"></i>首 页</a>
    <a href="/goods/list" {{"goods"|navactive}}><i class="visible-elements webicon icon-goods"></i>商品荟</a>
    <a href="/member/index/index" {{"member"|navactive}}><i class="visible-elements webicon icon-member"></i>商城会员</a> 
  </div>                                    
</div>
