<div class="hidden-elements navheader">
  <div class="container">
    <div class="navheader-left">
      <span class="tel">全国服务热线&nbsp;400-863-2766</span>
        <div class="nav-wxdiv" style="display:none">
          <i></i>
          <div>
            <img src="/assets/common/images/weixin.jpg">
          </div>
        </div>
      </span>
    </div>
    <div id="login-segment" class="navheader-right">
      <span>欢迎您来到分分钱商城！</span>
      <a class="text-login" href="/login">立即登录</a>
      <a class="text-regedit" href="/register">快速注册</a>
    </div>
  </div>
</div>

